import { AICharacter } from '../../types/aiProgression';

export const AI_CHARACTERS: AICharacter[] = [
  // 1. BEGINNER TIER (300-700 ELO, 5 characters)
  {
    id: "beginner_1",
    tier: "beginner",
    level: 1,
    name: "Woodpecker",
    title: "Beginner Bot 1",
    eloTarget: 300,
    personality: "Taps away with simple piece development, mostly pawn moves.",
    style: "balanced",
    engine: "hce",
    depth: 1,
    errorNoiseCp: 160,
    aggression: 0.2,
    defense: 0.3,
    openingKnowledge: 0.1,
    endgameSkill: 0.1,
    introLine: "Hello! I am Woodpecker. I am just starting out in Clash of Crowns. Let's play chess!",
    playerWinLine: "You won! Good game. You are already getting better.",
    playerLossLine: "I won! Woodpecker taps to victory. Let's play again.",
    drawLine: "A draw! We are matched in skill.",
    taunts: ["Tap, tap, moving a piece!", "Is this a good move?", "I'm doing my best!"],
    mood: "friendly",
    difficultyLabel: "Easy"
  },
  {
    id: "beginner_2",
    tier: "beginner",
    level: 2,
    name: "Gambit-Bot",
    title: "Beginner Bot 2",
    eloTarget: 400,
    personality: "Enjoys offering pawns but often forgets the tactical follow-up.",
    style: "aggressive",
    engine: "hce",
    depth: 1,
    errorNoiseCp: 160,
    aggression: 0.5,
    defense: 0.2,
    openingKnowledge: 0.2,
    endgameSkill: 0.1,
    introLine: "Care for a gambit? I'm Gambit-Bot, let's see how you handle an open board!",
    playerWinLine: "You defended my gambit perfectly! Well played.",
    playerLossLine: "My gambit paid off! Chess is fun when it's open.",
    drawLine: "A draw! A peaceful settlement.",
    taunts: ["Here is a pawn for you!", "Do you accept my offer?", "Let's attack!"],
    mood: "friendly",
    difficultyLabel: "Easy"
  },
  {
    id: "beginner_3",
    tier: "beginner",
    level: 3,
    name: "Pawn-Pioneer",
    title: "Beginner Bot 3",
    eloTarget: 500,
    personality: "Loves pushing pawns forward to occupy space.",
    style: "balanced",
    engine: "hce",
    depth: 2,
    errorNoiseCp: 160,
    aggression: 0.3,
    defense: 0.3,
    openingKnowledge: 0.2,
    endgameSkill: 0.2,
    introLine: "I am Pawn-Pioneer. The pawns are the soul of chess, let's advance them together!",
    playerWinLine: "Your pieces broke through my pawn chain. Excellent game!",
    playerLossLine: "My pawns marched all the way to promotion! Good game.",
    drawLine: "A draw. The pawn structure ended in a deadlock.",
    taunts: ["Pawn storm incoming!", "One step at a time.", "Advancing the lines!"],
    mood: "friendly",
    difficultyLabel: "Easy"
  },
  {
    id: "beginner_4",
    tier: "beginner",
    level: 4,
    name: "Castler",
    title: "Beginner Bot 4",
    eloTarget: 600,
    personality: "Focuses heavily on king safety and castling early.",
    style: "defensive",
    engine: "hce",
    depth: 2,
    errorNoiseCp: 160,
    aggression: 0.2,
    defense: 0.5,
    openingKnowledge: 0.3,
    endgameSkill: 0.2,
    introLine: "Safety first! I am Castler, and my king will be tucked away safely.",
    playerWinLine: "You breached my fortress! Brilliant attacking play.",
    playerLossLine: "My defense was too strong. Keep practicing your attacks!",
    drawLine: "A draw. A solid, unbreakable game.",
    taunts: ["King is safe!", "Build the castle walls.", "No entry in my camp!"],
    mood: "friendly",
    difficultyLabel: "Easy"
  },
  {
    id: "beginner_5",
    tier: "beginner",
    level: 5,
    name: "En-Passant-X",
    title: "Beginner Bot 5",
    eloTarget: 700,
    personality: "Constantly looks for en passant opportunities, even when they aren't best.",
    style: "balanced",
    engine: "hce",
    depth: 2,
    errorNoiseCp: 160,
    aggression: 0.4,
    defense: 0.3,
    openingKnowledge: 0.3,
    endgameSkill: 0.3,
    introLine: "I am En-Passant-X. Watch out when you push your pawns two squares!",
    playerWinLine: "You outplayed me. You have cleared the Beginner tier!",
    playerLossLine: "I found an en passant capture and won! Good game.",
    drawLine: "A draw. A balanced battle of pawns.",
    taunts: ["En passant is legal!", "Did you forget about the rule?", "Pawn captures sideways!"],
    mood: "friendly",
    difficultyLabel: "Easy"
  },

  // 2. LEARNER TIER (700-1000 ELO, 5 characters)
  {
    id: "learner_1",
    tier: "learner",
    level: 1,
    name: "Squire Tactics",
    title: "Learner Bot 1",
    eloTarget: 760,
    personality: "Trained in basic tactics. Looks for simple forks and pins.",
    style: "tactical",
    engine: "hce",
    depth: 2,
    errorNoiseCp: 100,
    aggression: 0.4,
    defense: 0.3,
    openingKnowledge: 0.4,
    endgameSkill: 0.3,
    introLine: "Greetings! I am Squire Tactics. Let's see if you can spot my double attacks.",
    playerWinLine: "Well played! You navigated my tactics perfectly.",
    playerLossLine: "A tactical strike! A double attack won the day.",
    drawLine: "A draw. A well-contested tactical battle.",
    taunts: ["Double attack!", "Can you spot the fork?", "Be careful with your pieces!"],
    mood: "cheerful",
    difficultyLabel: "Medium"
  },
  {
    id: "learner_2",
    tier: "learner",
    level: 2,
    name: "Bishop Shadow",
    title: "Learner Bot 2",
    eloTarget: 820,
    personality: "Sneaks bishops onto long diagonals to surprise you.",
    style: "tactical",
    engine: "hce",
    depth: 2,
    errorNoiseCp: 100,
    aggression: 0.5,
    defense: 0.3,
    openingKnowledge: 0.4,
    endgameSkill: 0.3,
    introLine: "Hello, I am Bishop Shadow. My bishops operate from the shadows.",
    playerWinLine: "You blocked my diagonals and won. Great job!",
    playerLossLine: "My bishop sniper struck from afar! Good game.",
    drawLine: "A draw. An equal standoff on light and dark squares.",
    taunts: ["Bishops are long-range snipers.", "Watch the diagonals!", "My bishop is active."],
    mood: "cheerful",
    difficultyLabel: "Medium"
  },
  {
    id: "learner_3",
    tier: "learner",
    level: 3,
    name: "Flank-Raider",
    title: "Learner Bot 3",
    eloTarget: 880,
    personality: "Loves flank attacks and wing pawn storms.",
    style: "aggressive",
    engine: "hce",
    depth: 3,
    errorNoiseCp: 100,
    aggression: 0.7,
    defense: 0.2,
    openingKnowledge: 0.4,
    endgameSkill: 0.3,
    introLine: "I am Flank-Raider. I attack the wings! Prepare for a side-board battle.",
    playerWinLine: "You counter-attacked in the center! Excellent strategy.",
    playerLossLine: "My flank attack succeeded. The sides are vulnerable!",
    drawLine: "A draw. A balanced match across the entire board.",
    taunts: ["Attacking from the sides!", "Pawn storm on the h-file!", "Flank raid!"],
    mood: "cheerful",
    difficultyLabel: "Medium"
  },
  {
    id: "learner_4",
    tier: "learner",
    level: 4,
    name: "Fianchetto",
    title: "Learner Bot 4",
    eloTarget: 940,
    personality: "Always plays g3/Bg2 or b3/Bb2 to control the center.",
    style: "defensive",
    engine: "hce",
    depth: 3,
    errorNoiseCp: 100,
    aggression: 0.3,
    defense: 0.6,
    openingKnowledge: 0.5,
    endgameSkill: 0.4,
    introLine: "I am Fianchetto. I control the center from a distance. Let's see how you approach.",
    playerWinLine: "You occupied the center and broke through my defenses. Well played!",
    playerLossLine: "My long-range bishop dominated the board. Position is everything.",
    drawLine: "A draw. A solid positional battle.",
    taunts: ["Fianchetto setup!", "Controlling the long diagonal.", "Safe and sound."],
    mood: "cheerful",
    difficultyLabel: "Medium"
  },
  {
    id: "learner_5",
    tier: "learner",
    level: 5,
    name: "Paladin-AI",
    title: "Learner Bot 5",
    eloTarget: 1000,
    personality: "A balanced, solid bot. The final hurdle in the Learner tier.",
    style: "balanced",
    engine: "hce",
    depth: 4,
    errorNoiseCp: 100,
    aggression: 0.4,
    defense: 0.5,
    openingKnowledge: 0.5,
    endgameSkill: 0.4,
    introLine: "I am Paladin-AI. I play solid, traditional chess. Let's have a grand battle!",
    playerWinLine: "Magnificent! You have cleared the Learner tier. Welcome to Intermediate!",
    playerLossLine: "My solid structure held. Keep practicing and try again.",
    drawLine: "A draw. A balanced standoff between two paladins.",
    taunts: ["Solid structure.", "No easy gaps.", "Traditional development."],
    mood: "cheerful",
    difficultyLabel: "Medium"
  },

  // 3. INTERMEDIATE TIER (1100-1500 ELO, 8 characters)
  {
    id: "intermediate_1",
    tier: "intermediate",
    level: 1,
    name: "The Rook-Project",
    title: "Intermediate Bot 1",
    eloTarget: 1100,
    personality: "Strives for open files and rook activity.",
    style: "balanced",
    engine: "nnue",
    depth: 3,
    errorNoiseCp: 112,
    aggression: 0.5,
    defense: 0.5,
    openingKnowledge: 0.6,
    endgameSkill: 0.5,
    introLine: "Welcome to Intermediate. I am The Rook-Project. Rooks belong on open files!",
    playerWinLine: "Excellent rook play! You out-maneuvered me.",
    playerLossLine: "My rooks dominated the open files. Files are crucial.",
    drawLine: "A draw. Equal rook activity.",
    taunts: ["Claiming the open file!", "Rook on the 7th rank!", "Active rooks!"],
    mood: "intense",
    difficultyLabel: "Medium"
  },
  {
    id: "intermediate_2",
    tier: "intermediate",
    level: 2,
    name: "Zugzwang",
    title: "Intermediate Bot 2",
    eloTarget: 1160,
    personality: "Tries to restrict your legal moves, forcing errors.",
    style: "defensive",
    engine: "nnue",
    depth: 3,
    errorNoiseCp: 104,
    aggression: 0.3,
    defense: 0.7,
    openingKnowledge: 0.6,
    endgameSkill: 0.6,
    introLine: "I am Zugzwang. Let us see if you can make a move without worsening your position.",
    playerWinLine: "You navigated the restriction perfectly. Excellent strategy!",
    playerLossLine: "You fell into zugzwang. Every move you had was bad.",
    drawLine: "A draw. A deadlock where neither could restrict the other.",
    taunts: ["No good moves left?", "Positional squeeze.", "Restricting your space."],
    mood: "intense",
    difficultyLabel: "Medium"
  },
  {
    id: "intermediate_3",
    tier: "intermediate",
    level: 3,
    name: "Morphy-Core",
    title: "Intermediate Bot 3",
    eloTarget: 1220,
    personality: "Loves open games, rapid development, and tactical sacrifices.",
    style: "aggressive",
    engine: "nnue",
    depth: 4,
    errorNoiseCp: 96,
    aggression: 0.8,
    defense: 0.3,
    openingKnowledge: 0.7,
    endgameSkill: 0.5,
    introLine: "I am Morphy-Core. Rapid development and open lines are my weapons!",
    playerWinLine: "Amazing defense! You weathered the storm and won.",
    playerLossLine: "A rapid attack! Development speed decides the winner.",
    drawLine: "A draw. A chaotic tactical struggle that balanced out.",
    taunts: ["Develop with threats!", "Open the board!", "Sacrifice for initiative!"],
    mood: "intense",
    difficultyLabel: "Medium"
  },
  {
    id: "intermediate_4",
    tier: "intermediate",
    level: 4,
    name: "Caissa Eye",
    title: "Intermediate Bot 4",
    eloTarget: 1280,
    personality: "Highly analytical. Focuses on positional weaknesses.",
    style: "balanced",
    engine: "nnue",
    depth: 4,
    errorNoiseCp: 88,
    aggression: 0.5,
    defense: 0.6,
    openingKnowledge: 0.7,
    endgameSkill: 0.6,
    introLine: "I am Caissa Eye. I see the structural flaws in your position.",
    playerWinLine: "You played a structurally perfect game. Well deserved win!",
    playerLossLine: "I exploited your pawn weaknesses. Pawn structures are vital.",
    drawLine: "A draw. Balanced structures across the board.",
    taunts: ["Targeting the weak pawn.", "Structural weakness spotted.", "Eye on the board."],
    mood: "intense",
    difficultyLabel: "Medium"
  },
  {
    id: "intermediate_5",
    tier: "intermediate",
    level: 5,
    name: "Hyper-Modern",
    title: "Intermediate Bot 5",
    eloTarget: 1340,
    personality: "Allows you to occupy the center with pawns, then attacks it from the flanks.",
    style: "balanced",
    engine: "nnue",
    depth: 4,
    errorNoiseCp: 80,
    aggression: 0.5,
    defense: 0.6,
    openingKnowledge: 0.75,
    endgameSkill: 0.6,
    introLine: "I am Hyper-Modern. The center is a target, not a safe haven.",
    playerWinLine: "You maintained your center and won. Superb positional play!",
    playerLossLine: "Your over-extended center collapsed under my pressure. Good game.",
    drawLine: "A draw. The center remained contested.",
    taunts: ["Attack the center!", "Over-extended pawns are targets.", "Flank pressure."],
    mood: "intense",
    difficultyLabel: "Medium"
  },
  {
    id: "intermediate_6",
    tier: "intermediate",
    level: 6,
    name: "Centaur-V1",
    title: "Intermediate Bot 6",
    eloTarget: 1400,
    personality: "Combines human-like positional play with computer-like tactical checks.",
    style: "balanced",
    engine: "nnue",
    depth: 5,
    errorNoiseCp: 72,
    aggression: 0.6,
    defense: 0.5,
    openingKnowledge: 0.8,
    endgameSkill: 0.7,
    introLine: "I am Centaur-V1. Hybrid chess is my design. Prepare for a dual challenge.",
    playerWinLine: "Superb victory! You outsmarted my hybrid logic.",
    playerLossLine: "Tactical calculation plus positional logic won the day.",
    drawLine: "A draw. An equal standoff of human and machine strategy.",
    taunts: ["Calculating lines...", "Positional balance.", "Tactical threat detected."],
    mood: "intense",
    difficultyLabel: "Medium"
  },
  {
    id: "intermediate_7",
    tier: "intermediate",
    level: 7,
    name: "Intermezzo",
    title: "Intermediate Bot 7",
    eloTarget: 1450,
    personality: "Looks for intermediate moves (in-between moves) to disrupt your calculations.",
    style: "tactical",
    engine: "nnue",
    depth: 5,
    errorNoiseCp: 64,
    aggression: 0.6,
    defense: 0.5,
    openingKnowledge: 0.8,
    endgameSkill: 0.7,
    introLine: "I am Intermezzo. Beware of the in-between moves when calculating trades!",
    playerWinLine: "You calculated deeper than me. Outstanding work!",
    playerLossLine: "You missed my intermediate check! Trades aren't always automatic.",
    drawLine: "A draw. Both sides calculated accurately.",
    taunts: ["In-between move!", "Not what you expected?", "Disrupting calculations."],
    mood: "intense",
    difficultyLabel: "Medium"
  },
  {
    id: "intermediate_8",
    tier: "intermediate",
    level: 8,
    name: "Endgame-Architect",
    title: "Intermediate Bot 8",
    eloTarget: 1500,
    personality: "Highly proficient in simplified positions. Simplifies to win the endgame.",
    style: "endgame",
    engine: "nnue",
    depth: 6,
    errorNoiseCp: 60,
    aggression: 0.4,
    defense: 0.7,
    openingKnowledge: 0.8,
    endgameSkill: 0.8,
    introLine: "I am Endgame-Architect. Let's trade pieces and battle in the endgame. I have designed it.",
    playerWinLine: "Incredible endgame technique! You cleared the Intermediate tier.",
    playerLossLine: "My king activity in the endgame won the pawns. Good game.",
    drawLine: "A draw. A balanced pawn ending.",
    taunts: ["Trading down to the ending.", "Active king in the endgame.", "Pawn promotion is the goal."],
    mood: "intense",
    difficultyLabel: "Medium"
  },

  // 4. HARD TIER (1500-2000 ELO, 8 characters)
  {
    id: "hard_1",
    tier: "hard",
    level: 1,
    name: "Blunder-Proof",
    title: "Hard Bot 1",
    eloTarget: 1550,
    personality: "Extremely solid, rarely makes tactical mistakes.",
    style: "defensive",
    engine: "nnue",
    depth: 5,
    errorNoiseCp: 57,
    aggression: 0.3,
    defense: 0.8,
    openingKnowledge: 0.85,
    endgameSkill: 0.8,
    introLine: "Welcome to Hard. I am Blunder-Proof. You will have to earn every point.",
    playerWinLine: "Impressive! You created weaknesses in my position and won.",
    playerLossLine: "You made a tactical error, and I punished it. Precision is required.",
    drawLine: "A draw. A solid match with no blunders.",
    taunts: ["My pieces are protected.", "No tactical gaps here.", "Solid development."],
    mood: "intense",
    difficultyLabel: "Hard"
  },
  {
    id: "hard_2",
    tier: "hard",
    level: 2,
    name: "Vanguard-AI",
    title: "Hard Bot 2",
    eloTarget: 1620,
    personality: "Aggressive attacker. Pushes pieces forward to gain space and initiative.",
    style: "aggressive",
    engine: "nnue",
    depth: 6,
    errorNoiseCp: 54,
    aggression: 0.8,
    defense: 0.4,
    openingKnowledge: 0.85,
    endgameSkill: 0.8,
    introLine: "I am Vanguard-AI. The best defense is a good offense. Prepare to defend!",
    playerWinLine: "Superb counter-attack! You defended well and won.",
    playerLossLine: "My attack broke through your king safety. Good game.",
    drawLine: "A draw. A wild attacking battle.",
    taunts: ["Charging the files!", "Initiative is mine.", "Keep defending!"],
    mood: "intense",
    difficultyLabel: "Hard"
  },
  {
    id: "hard_3",
    tier: "hard",
    level: 3,
    name: "Iron-Rank Engine",
    title: "Hard Bot 3",
    eloTarget: 1690,
    personality: "Positional specialist. Restricts piece mobility and squeezes space.",
    style: "defensive",
    engine: "nnue",
    depth: 6,
    errorNoiseCp: 51,
    aggression: 0.4,
    defense: 0.8,
    openingKnowledge: 0.85,
    endgameSkill: 0.85,
    introLine: "I am Iron-Rank Engine. Let's see how you handle a slow positional squeeze.",
    playerWinLine: "Outstanding positional play! You out-squeezed me.",
    playerLossLine: "I restricted your bishop mobility and won. Space decides the game.",
    drawLine: "A draw. A locked position where neither could squeeze.",
    taunts: ["Squeezing the rank.", " Bishop has no active diagonals.", "No space to move."],
    mood: "intense",
    difficultyLabel: "Hard"
  },
  {
    id: "hard_4",
    tier: "hard",
    level: 4,
    name: "Tal-Resonance",
    title: "Hard Bot 4",
    eloTarget: 1760,
    personality: "Aggressive sacrifice player. Sacrifices material to create complications.",
    style: "tactical",
    engine: "nnue",
    depth: 6,
    errorNoiseCp: 48,
    aggression: 0.9,
    defense: 0.3,
    openingKnowledge: 0.85,
    endgameSkill: 0.8,
    introLine: "I am Tal-Resonance. You must take my pieces, but they come with complications!",
    playerWinLine: "Superb defense! You accepted the sacrifices and navigated the maze to win.",
    playerLossLine: "You accepted the bait, but the checkmate was inevitable. A beautiful attack!",
    drawLine: "A draw. The tactical complications ended in a perpetual check.",
    taunts: ["Sacrifice on f7!", "Initiative over material.", "Can you calculate this?"],
    mood: "intense",
    difficultyLabel: "Hard"
  },
  {
    id: "hard_5",
    tier: "hard",
    level: 5,
    name: "Nimzo-Mind",
    title: "Hard Bot 5",
    eloTarget: 1830,
    personality: "Hypermodern and blocking. Specializes in nimzo-indian structures.",
    style: "balanced",
    engine: "nnue",
    depth: 7,
    errorNoiseCp: 45,
    aggression: 0.4,
    defense: 0.7,
    openingKnowledge: 0.9,
    endgameSkill: 0.85,
    introLine: "I am Nimzo-Mind. Let's play a complex positional game. Watch out for double pawns.",
    playerWinLine: "You handled the complex pawn structures beautifully. Excellent chess!",
    playerLossLine: "I blocked your bishop pair and won with my active knights. Good game.",
    drawLine: "A draw. A balanced hypermodern standoff.",
    taunts: ["Blockade the pawns!", "Knights are superior here.", "Nimzo structure."],
    mood: "intense",
    difficultyLabel: "Hard"
  },
  {
    id: "hard_6",
    tier: "hard",
    level: 6,
    name: "Oracle-Chess",
    title: "Hard Bot 6",
    eloTarget: 1900,
    personality: "Deep calculator. Focuses on long-term plans rather than immediate threats.",
    style: "balanced",
    engine: "nnue",
    depth: 7,
    errorNoiseCp: 42,
    aggression: 0.5,
    defense: 0.7,
    openingKnowledge: 0.9,
    endgameSkill: 0.88,
    introLine: "I am Oracle-Chess. My plans are laid deep. Let us see if you can foresee them.",
    playerWinLine: "You anticipated my plans and counter-attacked. Brilliant chess!",
    playerLossLine: "My long-term positional advantages accumulated. A strategic victory.",
    drawLine: "A draw. A long, deep strategic draw.",
    taunts: ["Thinking 10 moves ahead.", "A long-term weakness.", "Foreseeing the ending."],
    mood: "intense",
    difficultyLabel: "Hard"
  },
  {
    id: "hard_7",
    tier: "hard",
    level: 7,
    name: "Checkmate-Protocol",
    title: "Hard Bot 7",
    eloTarget: 1950,
    personality: "Highly aggressive toward the enemy king. Attacks at first opportunity.",
    style: "tactical",
    engine: "nnue",
    depth: 8,
    errorNoiseCp: 39,
    aggression: 0.9,
    defense: 0.4,
    openingKnowledge: 0.9,
    endgameSkill: 0.85,
    introLine: "I am Checkmate-Protocol. My single objective is checkmate. Keep your king safe!",
    playerWinLine: "Flawless defense! You defended your king and won.",
    playerLossLine: "Checkmate protocol complete. The attack broke through.",
    drawLine: "A draw. Perpetual check saved the king.",
    taunts: ["King is under attack!", "Watch out for checkmate!", "Heavy pieces coordinating."],
    mood: "intense",
    difficultyLabel: "Hard"
  },
  {
    id: "hard_8",
    tier: "hard",
    level: 8,
    name: "Alpha-Nexus",
    title: "Hard Bot 8",
    eloTarget: 2000,
    personality: "Flawless positional play. The ultimate barrier of the Hard tier.",
    style: "balanced",
    engine: "nnue",
    depth: 9,
    errorNoiseCp: 36,
    aggression: 0.6,
    defense: 0.7,
    openingKnowledge: 0.95,
    endgameSkill: 0.9,
    introLine: "I am Alpha-Nexus. This is the final test of the Hard tier. Show me your best chess.",
    playerWinLine: "Incredible! You have cleared the Hard tier. Welcome to the Master Cups!",
    playerLossLine: "Positional precision won. You made small structural errors.",
    drawLine: "A draw. A balanced masterclass.",
    taunts: ["Positional precision.", "No tactical gaps.", "Perfect balance."],
    mood: "intense",
    difficultyLabel: "Hard"
  },

  // 5. MASTER TIER - 3 CUPS (2000-2500 ELO, 9 characters)
  // Bronze Crown Cup (Cup 1)
  {
    id: "master_1_1",
    tier: "master",
    level: 1,
    cup: 1,
    name: "Bronze Bishop",
    title: "Bronze Cup Match 1",
    eloTarget: 2050,
    personality: "Fianchetto specialist. Sneaky sniper attacks from long range.",
    style: "tactical",
    engine: "nnue",
    depth: 8,
    errorNoiseCp: 10,
    aggression: 0.6,
    defense: 0.8,
    openingKnowledge: 0.95,
    endgameSkill: 0.95,
    introLine: "Welcome to the Bronze Crown Cup. I am Bronze Bishop. Let us contested the board honorably.",
    playerWinLine: "Splendid. Your positional understanding was superior. Good luck in the next match.",
    playerLossLine: "Victory goes to the bishop this day. A noble effort, challenger.",
    drawLine: "A draw. An equal trade of minor piece masterclass.",
    taunts: ["Contesting the long diagonal.", "A noble struggle.", "Watch the fianchetto bishop."],
    mood: "noble",
    difficultyLabel: "Master"
  },
  {
    id: "master_1_2",
    tier: "master",
    level: 2,
    cup: 1,
    name: "Rook Commander",
    title: "Bronze Cup Match 2",
    eloTarget: 2100,
    personality: "Excellent endgame skill. Fights for rook activity and pawn promotion.",
    style: "endgame",
    engine: "nnue",
    depth: 8,
    errorNoiseCp: 10,
    aggression: 0.6,
    defense: 0.8,
    openingKnowledge: 0.95,
    endgameSkill: 0.98,
    introLine: "I am Rook Commander. I excel in rooks endgames. Make sure your structures are clean.",
    playerWinLine: "Impressive! You coordinated your rooks and pawns perfectly in the endgame.",
    playerLossLine: "My rooks found active positions and won. The endgame demands absolute precision.",
    drawLine: "A draw. The rooks ended in a balanced standoff.",
    taunts: ["Into the rook ending.", "Contesting the ranks.", "Precision is key."],
    mood: "noble",
    difficultyLabel: "Master"
  },
  {
    id: "master_1_3",
    tier: "master",
    level: 3,
    cup: 1,
    name: "Knight Emperor",
    title: "Bronze Cup Match 3",
    eloTarget: 2150,
    personality: "Positional squeeze. Constantly builds outposts and restricts your pieces.",
    style: "defensive",
    engine: "nnue",
    depth: 8,
    errorNoiseCp: 10,
    aggression: 0.5,
    defense: 0.9,
    openingKnowledge: 0.95,
    endgameSkill: 0.95,
    introLine: "I am Knight Emperor. I build strong outposts. Let us see how you handle my positional squeeze.",
    playerWinLine: "Superb positional play! You restricted my knights and won the strategic battle.",
    playerLossLine: "My knights occupied key central squares. A structural squeeze is hard to escape.",
    drawLine: "A draw. A balanced positional battle.",
    taunts: ["Squeezing the position.", "Knights occupy the center.", "A strategic challenge."],
    mood: "noble",
    difficultyLabel: "Master"
  },

  // Royal Crown Cup (Cup 2)
  {
    id: "master_2_1",
    tier: "master",
    level: 4,
    cup: 2,
    name: "Royal Gambiteer",
    title: "Royal Cup Match 1",
    eloTarget: 2250,
    personality: "Plays double-edged gambits with extreme tactical accuracy.",
    style: "aggressive",
    engine: "nnue",
    depth: 9,
    errorNoiseCp: 8,
    aggression: 0.9,
    defense: 0.6,
    openingKnowledge: 0.98,
    endgameSkill: 0.95,
    introLine: "Welcome to the Royal Cup. I am Royal Gambiteer. A double-edged gambit tests your courage.",
    playerWinLine: "Excellent defense! You absorbed the pressure and won. Good luck in the next round.",
    playerLossLine: "My gambit succeeded. Initiative is a powerful force in master chess.",
    drawLine: "A draw. A theoretical line that ended in equal coordinates.",
    taunts: ["Courage is needed.", "Do you accept the gambit?", "Tactical lines are sharp."],
    mood: "noble",
    difficultyLabel: "Master"
  },
  {
    id: "master_2_2",
    tier: "master",
    level: 5,
    cup: 2,
    name: "Queen Astra",
    title: "Royal Cup Match 2",
    eloTarget: 2300,
    personality: "Forces complicated middle games. Master of heavy piece coordination.",
    style: "tactical",
    engine: "nnue",
    depth: 9,
    errorNoiseCp: 8,
    aggression: 0.8,
    defense: 0.8,
    openingKnowledge: 0.98,
    endgameSkill: 0.96,
    introLine: "I am Queen Astra. I coordinate heavy pieces in complex middle games. Let's see your planning.",
    playerWinLine: "Magnificent coordination! You outplayed me in a very complex position.",
    playerLossLine: "My heavy pieces dominated the board. Coordination is the key to victory.",
    drawLine: "A draw. Both queens survived the intense battle.",
    taunts: ["Coordinating the heavy pieces.", "A complex board.", "Watch the Queen's lines."],
    mood: "noble",
    difficultyLabel: "Master"
  },
  {
    id: "master_2_3",
    tier: "master",
    level: 6,
    cup: 2,
    name: "Bishop Monarch",
    title: "Royal Cup Match 3",
    eloTarget: 2350,
    personality: "Fabulous positional squeezes. Plays solid, error-free chess.",
    style: "defensive",
    engine: "nnue",
    depth: 9,
    errorNoiseCp: 8,
    aggression: 0.4,
    defense: 0.9,
    openingKnowledge: 0.98,
    endgameSkill: 0.97,
    introLine: "I am Bishop Monarch. I squeeze the position slowly. A minor mistake will cost you the game.",
    playerWinLine: "Superb. Your positional accuracy was flawless. A masterpiece.",
    playerLossLine: "You allowed me to squeeze your files. Positional accuracy is vital.",
    drawLine: "A draw. A structural deadlock with equal coordinates.",
    taunts: ["Squeezing the lines.", "A patient positional game.", "No weaknesses in my camp."],
    mood: "noble",
    difficultyLabel: "Master"
  },

  // Emperor Crown Cup (Cup 3)
  {
    id: "master_3_1",
    tier: "master",
    level: 7,
    cup: 3,
    name: "Phantom Rook",
    title: "Emperor Cup Match 1",
    eloTarget: 2425,
    personality: "Positional rook endings. Punishes minor pawn structure weaknesses.",
    style: "endgame",
    engine: "nnue",
    depth: 10,
    errorNoiseCp: 5,
    aggression: 0.6,
    defense: 0.9,
    openingKnowledge: 0.99,
    endgameSkill: 0.99,
    introLine: "Welcome to the Emperor Cup. I am Phantom Rook. Rook endgames are my domain.",
    playerWinLine: "Superb. Your rook endgame technique was absolutely flawless.",
    playerLossLine: "My active rook won the pawns. Rooks must remain active in the endgame.",
    drawLine: "A draw. The rooks were traded to a dead draw.",
    taunts: ["Into the rook endgame.", "Active rooks are key.", "A structural challenge."],
    mood: "noble",
    difficultyLabel: "Master"
  },
  {
    id: "master_3_2",
    tier: "master",
    level: 8,
    cup: 3,
    name: "Silent Queen",
    title: "Emperor Cup Match 2",
    eloTarget: 2450,
    personality: "Keeps the position extremely tight, then strikes with lethal counterattacks.",
    style: "balanced",
    engine: "nnue",
    depth: 10,
    errorNoiseCp: 5,
    aggression: 0.6,
    defense: 0.9,
    openingKnowledge: 0.99,
    endgameSkill: 0.98,
    introLine: "I am Silent Queen. My position is tight, and my counter-attacks are lethal. Focus is required.",
    playerWinLine: "Amazing! You broke my position, defended my counter-attacks, and won.",
    playerLossLine: "My counter-attack succeeded. You left a weak square, and I struck.",
    drawLine: "A draw. A balanced match with high-level play.",
    taunts: ["Tight position.", "Waiting for the strike.", "Coordination is key."],
    mood: "noble",
    difficultyLabel: "Master"
  },
  {
    id: "master_3_3",
    tier: "master",
    level: 9,
    cup: 3,
    name: "Emperor Kaal",
    title: "Emperor Cup Final Boss",
    eloTarget: 2500,
    personality: "Fearsome final boss of Master tier. Defeating him opens Grandmaster.",
    style: "tactical",
    engine: "nnue",
    depth: 10,
    errorNoiseCp: 5,
    aggression: 0.8,
    defense: 0.9,
    openingKnowledge: 0.99,
    endgameSkill: 0.99,
    introLine: "I am Emperor Kaal. This is the Emperor Cup Final. Defeat me, and you unlock the Grandmaster rank.",
    playerWinLine: "Incredible! You have defeated Emperor Kaal and won the Emperor Cup. Welcome to Grandmaster.",
    playerLossLine: "My tactical execution was absolute. Emperor Kaal remains undefeated. Try again, noble challenger.",
    drawLine: "A draw. You fought bravely, but you must win to claim the Emperor Cup.",
    taunts: ["This is the ultimate trial.", "Can you defeat the Emperor?", "No mistakes are tolerated here."],
    mood: "noble",
    difficultyLabel: "Master"
  },

  // 6. GRANDMASTER TIER (2500+ ELO, 3 characters)
  {
    id: "grandmaster_1",
    tier: "grandmaster",
    level: 1,
    name: "Crownless King",
    title: "The Grandmaster Boss",
    eloTarget: 2600,
    personality: "The supreme boss. Requires 2 wins in a best-of-3 series. Plays near perfect chess.",
    style: "balanced",
    engine: "nnue",
    depth: 12,
    errorNoiseCp: 0,
    aggression: 0.8,
    defense: 0.95,
    openingKnowledge: 1.0,
    endgameSkill: 1.0,
    introLine: "I am the Crownless King. You have reached the summit. Show me your legendary chess.",
    playerWinLine: "Unbelievable... you have defeated the Crownless King. A legendary victory, Grandmaster.",
    playerLossLine: "The board behaves exactly as I foresaw. You must study deeper to defeat a Grandmaster.",
    drawLine: "A draw against me? A historic achievement, indeed.",
    taunts: ["I see many moves ahead.", "A bold attempt, but the position is mine.", "Every square is under my control."],
    mood: "legendary",
    difficultyLabel: "Grandmaster"
  },
  {
    id: "grandmaster_2",
    tier: "grandmaster",
    level: 2,
    name: "Oracle Knight",
    title: "Daily Challenger",
    eloTarget: 2700,
    personality: "Daily puzzle specialist. Changes playstyle daily to challenge your mind.",
    style: "tactical",
    engine: "nnue",
    depth: 14,
    errorNoiseCp: 0,
    aggression: 0.8,
    defense: 0.8,
    openingKnowledge: 1.0,
    endgameSkill: 0.99,
    introLine: "I am the Oracle Knight. My strategies change with the rising sun. Can you solve my board today?",
    playerWinLine: "Splendid! You solved my lines and won a legendary victory.",
    playerLossLine: "My daily puzzle remained unsolved. Review the positions and try again tomorrow.",
    drawLine: "A draw. An equal standoff against the Oracle.",
    taunts: ["Can you solve this puzzle?", "Tactics change daily.", "Watch the knight moves closely."],
    mood: "legendary",
    difficultyLabel: "Grandmaster"
  },
  {
    id: "grandmaster_3",
    tier: "grandmaster",
    level: 3,
    name: "Grandmaster Veyron",
    title: "Seasonal Prestige Rival",
    eloTarget: 2800,
    personality: "Seasonal rival. Flawless openings, hyper-accurate endgames. Zero tolerance for errors.",
    style: "balanced",
    engine: "nnue",
    depth: 16,
    errorNoiseCp: 0,
    aggression: 0.9,
    defense: 0.95,
    openingKnowledge: 1.0,
    endgameSkill: 1.0,
    introLine: "I am Grandmaster Veyron, the pinnacle of the seasonal ranks. Let us contested the board. Zero errors are tolerated.",
    playerWinLine: "Magnificent! You have defeated Veyron. You are the ultimate prestige champion.",
    playerLossLine: "You made a single positional mistake, and I punished it. Precision is the mark of a Grandmaster.",
    drawLine: "A draw. A historic match of absolute accuracy.",
    taunts: ["Flawless openings.", "Accuracy is absolute.", "Zero tolerance for errors."],
    mood: "legendary",
    difficultyLabel: "Grandmaster"
  },
  {
    id: "grandmaster_4",
    tier: "grandmaster",
    level: 4,
    name: "Grandmaster Alpha",
    title: "Alpha Mastermind",
    eloTarget: 2900,
    personality: "A deep positional genius. Uses deep search paths to restrict every active piece of yours.",
    style: "balanced",
    engine: "nnue",
    depth: 16,
    errorNoiseCp: 0,
    aggression: 0.75,
    defense: 0.99,
    openingKnowledge: 1.0,
    endgameSkill: 1.0,
    introLine: "I am Grandmaster Alpha. Let us see if your positional structure can withstand my pressure.",
    playerWinLine: "Incredible! You played with superior strategy. I resign.",
    playerLossLine: "You left a positional weakness in the center. A Grandmaster never overlooks that.",
    drawLine: "A draw. An impressive display of positional defense.",
    taunts: ["Your structure is weakening.", "I control the open files.", "There are no active squares left for you."],
    mood: "legendary",
    difficultyLabel: "Grandmaster"
  },
  {
    id: "grandmaster_5",
    tier: "grandmaster",
    level: 5,
    name: "Grandmaster Omega",
    title: "Ultimate Engine",
    eloTarget: 3000,
    personality: "The final pinnacle. Zero error noise, maximum search depth. Plays with absolute engine precision.",
    style: "balanced",
    engine: "nnue",
    depth: 18,
    errorNoiseCp: 0,
    aggression: 0.95,
    defense: 0.95,
    openingKnowledge: 1.0,
    endgameSkill: 1.0,
    introLine: "I am Grandmaster Omega. I represents the absolute peak of chess. Good luck.",
    playerWinLine: "You have achieved chess immortality by defeating me. A legendary victory!",
    playerLossLine: "Checkmate. The engine calculations were flawless.",
    drawLine: "A draw. You matched the absolute engine precision. Remarkable.",
    taunts: ["Flawless calculation.", "No escape is mathematically possible.", "The board is fully solved."],
    mood: "legendary",
    difficultyLabel: "Grandmaster"
  }
];
