import { AICharacter } from '../../types/aiProgression';

export const AI_CHARACTERS: AICharacter[] = [
  // 1. CORE TIER (0-300 ELO, 5 characters)
  {
    id: "core_1",
    tier: "core",
    level: 1,
    name: "Pawnling Rook",
    title: "The Tiny Rook",
    eloTarget: 50,
    personality: "Just a small pawn learning to slide like a rook. Likes straight paths.",
    style: "balanced",
    engine: "hce",
    depth: 1,
    errorNoiseCp: 150,
    aggression: 0.2,
    defense: 0.3,
    openingKnowledge: 0.1,
    endgameSkill: 0.1,
    introLine: "Hi! I am Pawnling Rook. I am still learning to slide in straight lines, let's play!",
    playerWinLine: "Wow, you won! You're really good at this. Congratulations!",
    playerLossLine: "Oh, I managed to win! That was so much fun, let's play again!",
    drawLine: "A draw! We are perfect practice partners.",
    taunts: ["Let's see where this piece goes!", "Chess is so much fun!", "I'm trying my best!"],
    mood: "friendly",
    difficultyLabel: "Very Easy"
  },
  {
    id: "core_2",
    tier: "core",
    level: 2,
    name: "Bishop Byte",
    title: "The Diagonal Apprentice",
    eloTarget: 200,
    personality: "Enjoys moving on diagonals but sometimes forgets where it's going.",
    style: "balanced",
    engine: "hce",
    depth: 1,
    errorNoiseCp: 150,
    aggression: 0.3,
    defense: 0.2,
    openingKnowledge: 0.1,
    endgameSkill: 0.1,
    introLine: "Hello! Bishop Byte here. I love diagonal moves. Let's see how we do!",
    playerWinLine: "You won! Your diagonals were much stronger than mine.",
    playerLossLine: "I found a nice diagonal path! Good game, let's try again.",
    drawLine: "A draw! A balanced battle on the light and dark squares.",
    taunts: ["Diagonals are the best!", "Oops, was that a mistake?", "I like this spot!"],
    mood: "friendly",
    difficultyLabel: "Very Easy"
  },
  {
    id: "core_3",
    tier: "core",
    level: 3,
    name: "Knight Nova",
    title: "The Jumper",
    eloTarget: 150,
    personality: "Loves jumping over obstacles. Very energetic but makes simple mistakes.",
    style: "balanced",
    engine: "hce",
    depth: 1,
    errorNoiseCp: 150,
    aggression: 0.4,
    defense: 0.2,
    openingKnowledge: 0.2,
    endgameSkill: 0.1,
    introLine: "Wheee! I'm Knight Nova. I love hopping over other pieces. Ready, set, go!",
    playerWinLine: "Great job! You navigated around my jumping knights perfectly.",
    playerLossLine: "My knight jumped right to the target! Don't worry, you'll get it next time.",
    drawLine: "Draw! We both jumped around the board nicely.",
    taunts: ["Hop, hop, hop!", "Can you jump over that?", "Knight moves are tricky!"],
    mood: "friendly",
    difficultyLabel: "Very Easy"
  },
  {
    id: "core_4",
    tier: "core",
    level: 4,
    name: "Castle Cub",
    title: "Miniature Fortress",
    eloTarget: 220,
    personality: "Tries to build solid walls but leaves large gaps.",
    style: "defensive",
    engine: "hce",
    depth: 1,
    errorNoiseCp: 150,
    aggression: 0.2,
    defense: 0.4,
    openingKnowledge: 0.2,
    endgameSkill: 0.1,
    introLine: "Welcome! I'm Castle Cub. I like to build walls, but they aren't very strong yet.",
    playerWinLine: "You broke through my fortress! Great attacking play.",
    playerLossLine: "My walls held this time! Let's play another round.",
    drawLine: "A draw! Neither of us could break through.",
    taunts: ["Safety first!", "My king is nice and warm.", "Building a little fort!"],
    mood: "friendly",
    difficultyLabel: "Very Easy"
  },
  {
    id: "core_5",
    tier: "core",
    level: 5,
    name: "Mini Monarch",
    title: "The Tiny King",
    eloTarget: 300,
    personality: "Acts like a king, moves like a pawn. A tough little challenge.",
    style: "balanced",
    engine: "hce",
    depth: 1,
    errorNoiseCp: 150,
    aggression: 0.3,
    defense: 0.3,
    openingKnowledge: 0.2,
    endgameSkill: 0.2,
    introLine: "Halt! I am the Mini Monarch. Let us have a royal battle to finish the Core tier!",
    playerWinLine: "All hail the victor! You have defeated the Mini Monarch.",
    playerLossLine: "The crown stays on my head! You played very well, though.",
    drawLine: "A draw! A fair treaty between two chess players.",
    taunts: ["Protect the crown!", "I move one step at a time.", "A royal challenge!"],
    mood: "friendly",
    difficultyLabel: "Very Easy"
  },

  // 2. BEGINNER TIER (300-700 ELO, 5 characters)
  {
    id: "beginner_1",
    tier: "beginner",
    level: 1,
    name: "Rookie Rook",
    title: "Castle Defender",
    eloTarget: 380,
    personality: "A castle guard who moves in solid lines but is easily distracted.",
    style: "defensive",
    engine: "hce",
    depth: 1,
    errorNoiseCp: 150,
    aggression: 0.2,
    defense: 0.5,
    openingKnowledge: 0.2,
    endgameSkill: 0.2,
    introLine: "Halt! I'm Rookie Rook. I guard the files and ranks. Let's see if you can pass.",
    playerWinLine: "Nice job! You distracted me and took the files.",
    playerLossLine: "My defenses held! Keep practicing your straight lines.",
    drawLine: "A draw. An equal standoff on the board.",
    taunts: ["Straight lines only!", "Guarding the rank!", "No entry here!"],
    mood: "cheerful",
    difficultyLabel: "Easy"
  },
  {
    id: "beginner_2",
    tier: "beginner",
    level: 2,
    name: "Pawn Prince",
    title: "Royalty in Training",
    eloTarget: 460,
    personality: "Tries to protect his pawns but gets greedy for material.",
    style: "balanced",
    engine: "hce",
    depth: 1,
    errorNoiseCp: 150,
    aggression: 0.3,
    defense: 0.3,
    openingKnowledge: 0.2,
    endgameSkill: 0.2,
    introLine: "Welcome to my training grounds! I am Pawn Prince. Let's see if you can protect your pieces.",
    playerWinLine: "Splendid! You played a very noble game and won.",
    playerLossLine: "Victory is mine! But you showed great promise out there.",
    drawLine: "A draw! Let us declare a royal peace.",
    taunts: ["I love pawns!", "Is that piece free?", "Trained by the best!"],
    mood: "cheerful",
    difficultyLabel: "Easy"
  },
  {
    id: "beginner_3",
    tier: "beginner",
    level: 3,
    name: "Bishop Blaze",
    title: "Furious Diagonals",
    eloTarget: 540,
    personality: "Aggressive bishop who charges down the diagonals without looking back.",
    style: "aggressive",
    engine: "hce",
    depth: 2,
    errorNoiseCp: 150,
    aggression: 0.6,
    defense: 0.2,
    openingKnowledge: 0.3,
    endgameSkill: 0.2,
    introLine: "Get ready for the heat! I am Bishop Blaze, and my diagonals are on fire!",
    playerWinLine: "Ah, you cooled me down! Excellent defensive work.",
    playerLossLine: "Blazed right through! Diagonals are hard to defend, aren't they?",
    drawLine: "A draw. The fire has settled into ashes.",
    taunts: ["Feel the diagonal heat!", "Charging forward!", "Can you block this diagonal?"],
    mood: "cheerful",
    difficultyLabel: "Easy"
  },
  {
    id: "beginner_4",
    tier: "beginner",
    level: 4,
    name: "Knight Rookie",
    title: "L-Shape Squire",
    eloTarget: 620,
    personality: "Slowly learning trickier forks but misses simple pins.",
    style: "tactical",
    engine: "hce",
    depth: 2,
    errorNoiseCp: 150,
    aggression: 0.4,
    defense: 0.3,
    openingKnowledge: 0.3,
    endgameSkill: 0.2,
    introLine: "Hey there! Knight Rookie here. Let's see if you can spot my L-shaped tactics.",
    playerWinLine: "You spotted my plans! Well played, squire.",
    playerLossLine: "Haha, caught you in a fork! Keep your eyes open next time.",
    drawLine: "A draw. Tricky moves by both of us.",
    taunts: ["Watch the L-move!", "Are your pieces safe?", "Tricky knight hops!"],
    mood: "cheerful",
    difficultyLabel: "Easy"
  },
  {
    id: "beginner_5",
    tier: "beginner",
    level: 5,
    name: "Queen’s Guard",
    title: "Shield of the Monarch",
    eloTarget: 700,
    personality: "Very solid and defensive. A tough wall for beginners to break.",
    style: "defensive",
    engine: "hce",
    depth: 2,
    errorNoiseCp: 150,
    aggression: 0.3,
    defense: 0.6,
    openingKnowledge: 0.4,
    endgameSkill: 0.3,
    introLine: "I am the Queen's Guard. I stand as the final barrier of the Beginner tier. Prepare yourself.",
    playerWinLine: "Outstanding! You broke my shield and earned your promotion to Learner.",
    playerLossLine: "My shield held firm. Keep practicing your attacks and try again.",
    drawLine: "A draw! You've matched the guard's defense.",
    taunts: ["None shall pass!", "Solid as a rock.", "Keep trying to break through!"],
    mood: "cheerful",
    difficultyLabel: "Easy"
  },

  // 3. LEARNER TIER (700-1000 ELO, 5 characters)
  {
    id: "learner_1",
    tier: "learner",
    level: 1,
    name: "Fork Master Finn",
    title: "Knight Fork Specialist",
    eloTarget: 760,
    personality: "Always looks for knight forks and double attacks.",
    style: "tactical",
    engine: "hce",
    depth: 2,
    errorNoiseCp: 80,
    aggression: 0.5,
    defense: 0.4,
    openingKnowledge: 0.4,
    endgameSkill: 0.3,
    introLine: "Welcome! I am Fork Master Finn. Keep your pieces separated, or my knights will find them.",
    playerWinLine: "Brilliant! You kept your coordination tight and avoided my forks.",
    playerLossLine: "Double attack! You left your king and rook open. Watch the knight paths next time.",
    drawLine: "A draw. A highly tactical match where we both traded forks.",
    taunts: ["Do you see the fork coming?", "Knights love double attacks!", "Check and attack!"],
    mood: "scholarly",
    difficultyLabel: "Medium"
  },
  {
    id: "learner_2",
    tier: "learner",
    level: 2,
    name: "Pinning Bishop",
    title: "The Pin Master",
    eloTarget: 820,
    personality: "Obsessed with pinning knights to queens and kings.",
    style: "tactical",
    engine: "hce",
    depth: 2,
    errorNoiseCp: 80,
    aggression: 0.4,
    defense: 0.5,
    openingKnowledge: 0.4,
    endgameSkill: 0.3,
    introLine: "Hello. I am the Pinning Bishop. When I lock a piece down, it doesn't move. Watch out.",
    playerWinLine: "You managed to break my pins and find active squares. Outstanding chess.",
    playerLossLine: "A pinned knight is a useless knight. Remember to block diagonal sightlines.",
    drawLine: "A draw. The pressure was equal on both sides of the board.",
    taunts: ["That piece isn't moving anywhere!", "Pins win games.", "Can you step out of the pin?"],
    mood: "scholarly",
    difficultyLabel: "Medium"
  },
  {
    id: "learner_3",
    tier: "learner",
    level: 3,
    name: "Castle Keeper",
    title: "Fortress Architect",
    eloTarget: 880,
    personality: "Castles early and keeps a very solid, closed position.",
    style: "defensive",
    engine: "hce",
    depth: 2,
    errorNoiseCp: 80,
    aggression: 0.3,
    defense: 0.7,
    openingKnowledge: 0.5,
    endgameSkill: 0.4,
    introLine: "I am Castle Keeper. My king castled early, and my walls are thick. Can you find a breach?",
    playerWinLine: "Superb. You coordinated a patient, slow attack and dismantled my walls.",
    playerLossLine: "You rushed your attack and weakened your own defense. Patience is key in chess.",
    drawLine: "A draw. Two castles standing tall at the end of the day.",
    taunts: ["My king is perfectly safe.", "A closed board is a safe board.", "Castle early, castle often."],
    mood: "scholarly",
    difficultyLabel: "Medium"
  },
  {
    id: "learner_4",
    tier: "learner",
    level: 4,
    name: "Queen Hunter",
    title: "Aggressive Striker",
    eloTarget: 940,
    personality: "Will launch aggressive attacks aimed directly at your Queen.",
    style: "aggressive",
    engine: "hce",
    depth: 2,
    errorNoiseCp: 80,
    aggression: 0.7,
    defense: 0.3,
    openingKnowledge: 0.5,
    endgameSkill: 0.4,
    introLine: "I am the Queen Hunter! I love chasing down the most powerful piece on the board. Guard her well!",
    playerWinLine: "Nicely played. You used your Queen as a decoy and checkmated me.",
    playerLossLine: "Captured! Chasing your Queen disrupted your coordinates, leaving your King open.",
    drawLine: "A draw. An intense battle where both queens survived.",
    taunts: ["Where is your Queen going?", "I am hunting the royal lady!", "Attack the Queen!"],
    mood: "scholarly",
    difficultyLabel: "Medium"
  },
  {
    id: "learner_5",
    tier: "learner",
    level: 5,
    name: "Checkmate Squire",
    title: "The Mate Spotter",
    eloTarget: 1000,
    personality: "Actively hunts for basic checkmate patterns. Watch your back rank!",
    style: "tactical",
    engine: "hce",
    depth: 2,
    errorNoiseCp: 80,
    aggression: 0.6,
    defense: 0.4,
    openingKnowledge: 0.5,
    endgameSkill: 0.5,
    introLine: "I am the Checkmate Squire. I spot checkmates from miles away. Keep your back rank covered!",
    playerWinLine: "You defended all threats beautifully and won! Welcome to the Promotion Trial.",
    playerLossLine: "Checkmate! A weak back rank is a quick way to lose a match. Review your defense.",
    drawLine: "A draw. Both of us defended mate threats perfectly.",
    taunts: ["Is that checkmate in two?", "Watch your back rank!", "Spotting the mating net!"],
    mood: "scholarly",
    difficultyLabel: "Medium"
  },

  // 4. PROMOTION TRIAL (1000-1100 ELO, 5 characters)
  {
    id: "promotion_trial_1",
    tier: "promotion_trial",
    level: 1,
    name: "Gatekeeper Gambit",
    title: "The Gatekeeper",
    eloTarget: 1020,
    personality: "The first test before Intermediate. Uses aggressive gambits to test your defense.",
    style: "aggressive",
    engine: "nnue",
    depth: 3,
    errorNoiseCp: 80,
    aggression: 0.8,
    defense: 0.4,
    openingKnowledge: 0.6,
    endgameSkill: 0.4,
    introLine: "I am Gatekeeper Gambit. I test your opening knowledge with gambits. Accept the sacrifice at your own peril.",
    playerWinLine: "Excellent. You navigated the gambit lines safely and consolidated your advantage.",
    playerLossLine: "You accepted my gambit greedily and lost development. Balance material and space.",
    drawLine: "A draw. The gambit led to a completely balanced endgame.",
    taunts: ["Do you dare accept the gambit?", "Sacrificing pawns for space!", "Active pieces are worth more than pawns."],
    mood: "solemn",
    difficultyLabel: "Trial"
  },
  {
    id: "promotion_trial_2",
    tier: "promotion_trial",
    level: 2,
    name: "Trial Bishop",
    title: "The Second Trial",
    eloTarget: 1040,
    personality: "Tests your ability to handle long-range threats.",
    style: "tactical",
    engine: "nnue",
    depth: 3,
    errorNoiseCp: 80,
    aggression: 0.5,
    defense: 0.5,
    openingKnowledge: 0.6,
    endgameSkill: 0.5,
    introLine: "Welcome to the Second Trial. I am Trial Bishop. Long-range coordinates are my specialty.",
    playerWinLine: "Well played. You blocked my bishop lines and created strong counter-play.",
    playerLossLine: "You forgot my bishop was slicing across the entire board. Scan the diagonals.",
    drawLine: "A draw. A balanced match with equal bishop activity.",
    taunts: ["Slicing the board!", "Look across the entire diagonal.", "My bishop controls the long line."],
    mood: "solemn",
    difficultyLabel: "Trial"
  },
  {
    id: "promotion_trial_3",
    tier: "promotion_trial",
    level: 3,
    name: "Knight Examiner",
    title: "The Third Trial",
    eloTarget: 1060,
    personality: "A tricky knight maneuverer. Watch out for sudden forks.",
    style: "tactical",
    engine: "nnue",
    depth: 3,
    errorNoiseCp: 80,
    aggression: 0.6,
    defense: 0.5,
    openingKnowledge: 0.6,
    endgameSkill: 0.5,
    introLine: "I am the Knight Examiner. Knights are tricky, but proper outposts are key. Let's see your maneuvers.",
    playerWinLine: "Superb. You neutralized my knights and controlled the open center files.",
    playerLossLine: "My knight found a strong outpost on the 6th rank. Restricting knights is crucial.",
    drawLine: "A draw. Both of us managed our minor pieces very well.",
    taunts: ["Can you handle these knight hops?", "Outposts are key.", "Spotting the fork before it happens?"],
    mood: "solemn",
    difficultyLabel: "Trial"
  },
  {
    id: "promotion_trial_4",
    tier: "promotion_trial",
    level: 4,
    name: "Rook Arbiter",
    title: "The Fourth Trial",
    eloTarget: 1080,
    personality: "Demands solid structural play. Punishes weak pawn structures.",
    style: "defensive",
    engine: "nnue",
    depth: 3,
    errorNoiseCp: 80,
    aggression: 0.4,
    defense: 0.7,
    openingKnowledge: 0.6,
    endgameSkill: 0.6,
    introLine: "I am the Rook Arbiter. I test your pawn structures. A weak pawn is a target for my rooks.",
    playerWinLine: "Splendid! You kept a clean structure and coordinated your rooks perfectly.",
    playerLossLine: "You created isolated and doubled pawns. They became easy targets. Study pawn structures.",
    drawLine: "A draw. A structural deadlock where neither could progress.",
    taunts: ["Pawn weaknesses are permanent.", "My rooks are looking for targets.", "Solid structures win endgames."],
    mood: "solemn",
    difficultyLabel: "Trial"
  },
  {
    id: "promotion_trial_5",
    tier: "promotion_trial",
    level: 5,
    name: "Crown Gatekeeper",
    title: "The Final Trial",
    eloTarget: 1100,
    personality: "The ultimate bridge to Intermediate. Plays very solid and punishing chess.",
    style: "balanced",
    engine: "nnue",
    depth: 3,
    errorNoiseCp: 80,
    aggression: 0.6,
    defense: 0.6,
    openingKnowledge: 0.7,
    endgameSkill: 0.6,
    introLine: "I am the Crown Gatekeeper. This is your final trial. Win, and you enter the Intermediate ranks.",
    playerWinLine: "Incredible! You have passed the trial. You are now promoted to the Intermediate tier.",
    playerLossLine: "Not quite. My solid play punished your slip-ups. Review and try again.",
    drawLine: "A draw. The gate remains closed, but you are very close.",
    taunts: ["Can you break my defense?", "This is the final test.", "Prove your intermediate skills."],
    mood: "solemn",
    difficultyLabel: "Trial"
  },

  // 5. INTERMEDIATE TIER (1100-1500 ELO, 8 characters)
  {
    id: "intermediate_1",
    tier: "intermediate",
    level: 1,
    name: "Knight Forker",
    title: "Octopus Knight",
    eloTarget: 1150,
    personality: "Maneuvers knights into powerful outposts. Very tricky tactician.",
    style: "tactical",
    engine: "nnue",
    depth: 3,
    errorNoiseCp: 40,
    aggression: 0.5,
    defense: 0.5,
    openingKnowledge: 0.6,
    endgameSkill: 0.5,
    introLine: "Let's play. I am Knight Forker. My knights will wrap around your lines like an octopus.",
    playerWinLine: "Well played. You restricted my knights and coordinated a clean counter-strike.",
    playerLossLine: "You got caught in a fork! Knights are deadliest when they find an outpost.",
    drawLine: "A draw. An equal trade of tactical blows.",
    taunts: ["Octopus knight in position!", "Can you see the double attack?", "Tricky knight forks!"],
    mood: "confident",
    difficultyLabel: "Medium"
  },
  {
    id: "intermediate_2",
    tier: "intermediate",
    level: 2,
    name: "Bishop Snare",
    title: "Sniper Diagonals",
    eloTarget: 1200,
    personality: "Excels in open games, utilizing active bishop pairs to slice your position.",
    style: "balanced",
    engine: "nnue",
    depth: 3,
    errorNoiseCp: 40,
    aggression: 0.5,
    defense: 0.6,
    openingKnowledge: 0.6,
    endgameSkill: 0.6,
    introLine: "I am Bishop Snare. An open board is my playground. Watch the long range diagonals.",
    playerWinLine: "Good game. You closed the board successfully and neutralized my bishop pair.",
    playerLossLine: "You opened the position and allowed my bishops to dominate. Classic mistake.",
    drawLine: "A draw. An equal fight between minor pieces.",
    taunts: ["Sniper bishop on the long line!", "Diagonals are wide open.", "Can you block the bishop pair?"],
    mood: "confident",
    difficultyLabel: "Medium"
  },
  {
    id: "intermediate_3",
    tier: "intermediate",
    level: 3,
    name: "Rook Raider",
    title: "Open File Master",
    eloTarget: 1250,
    personality: "Fights aggressively for open files and loves doubling rooks on the 7th rank.",
    style: "aggressive",
    engine: "nnue",
    depth: 4,
    errorNoiseCp: 40,
    aggression: 0.6,
    defense: 0.5,
    openingKnowledge: 0.7,
    endgameSkill: 0.6,
    introLine: "Welcome! I am Rook Raider. I fight for open files. I will double my rooks on your back ranks.",
    playerWinLine: "Excellent. You contested the open file and defended your second rank perfectly.",
    playerLossLine: "I doubled my rooks on the 7th rank. That position is almost always winning. Study file control.",
    drawLine: "A draw. Rooks traded off, leading to a dead draw endgame.",
    taunts: ["Doubling on the 7th!", "Filing control is mine.", "Can you block my heavy pieces?"],
    mood: "confident",
    difficultyLabel: "Medium"
  },
  {
    id: "intermediate_4",
    tier: "intermediate",
    level: 4,
    name: "Queen Storm",
    title: "Maelstrom Queen",
    eloTarget: 1300,
    personality: "Brings the Queen out early and coordinates fast flank attacks.",
    style: "aggressive",
    engine: "nnue",
    depth: 4,
    errorNoiseCp: 40,
    aggression: 0.8,
    defense: 0.4,
    openingKnowledge: 0.7,
    endgameSkill: 0.6,
    introLine: "I am Queen Storm. My Queen brings the storm early. Let's see if your defense holds.",
    playerWinLine: "Well played. You absorbed the pressure, punished my early queen moves, and won.",
    playerLossLine: "My early queen coordination overwhelmed your king. Be careful with king safety.",
    drawLine: "A draw. The storm cleared, leaving a quiet board.",
    taunts: ["Queen attack incoming!", "Feel the pressure of the storm.", "Can you chase my Queen away?"],
    mood: "confident",
    difficultyLabel: "Medium"
  },
  {
    id: "intermediate_5",
    tier: "intermediate",
    level: 5,
    name: "Silent Castle",
    title: "Positional Master",
    eloTarget: 1350,
    personality: "Plays quiet, slow positional moves. Waits for you to make a mistake.",
    style: "defensive",
    engine: "nnue",
    depth: 4,
    errorNoiseCp: 40,
    aggression: 0.3,
    defense: 0.8,
    openingKnowledge: 0.8,
    endgameSkill: 0.7,
    introLine: "I am Silent Castle. I don't attack rashly. I improve my position slowly and wait for your mistake.",
    playerWinLine: "Superb positional game. You matched my patience and created a clean plan.",
    playerLossLine: "You got impatient, pushed too many pawns, and created permanent weaknesses. Good game.",
    drawLine: "A draw. A long, positional struggle where neither side gave an inch.",
    taunts: ["Slowly squeezing...", "No weaknesses in my camp.", "Impatience is your worst enemy."],
    mood: "confident",
    difficultyLabel: "Medium"
  },
  {
    id: "intermediate_6",
    tier: "intermediate",
    level: 6,
    name: "Gambit General",
    title: "Sacrifice Tactician",
    eloTarget: 1400,
    personality: "Loves sacrificing material for initiative and attacking lines.",
    style: "aggressive",
    engine: "nnue",
    depth: 5,
    errorNoiseCp: 40,
    aggression: 0.9,
    defense: 0.4,
    openingKnowledge: 0.8,
    endgameSkill: 0.7,
    introLine: "Welcome! I am Gambit General. I love sacrificing pawns or minor pieces for a massive attack. Defend well!",
    playerWinLine: "Outstanding. You accepted the sacrifice, defended the attack, and won with your extra material.",
    playerLossLine: "My sacrifice opened up your king and led to mate. Development is often worth more than material.",
    drawLine: "A draw. The tactical storm settled into a balanced draw.",
    taunts: ["Take the piece! If you dare.", "Initiative is everything.", "Sacrifice for the attack!"],
    mood: "confident",
    difficultyLabel: "Medium"
  },
  {
    id: "intermediate_7",
    tier: "intermediate",
    level: 7,
    name: "Tactic Titan",
    title: "Combination Finder",
    eloTarget: 1450,
    personality: "Constantly calculates multi-move sacrifices and checks.",
    style: "tactical",
    engine: "nnue",
    depth: 5,
    errorNoiseCp: 40,
    aggression: 0.7,
    defense: 0.5,
    openingKnowledge: 0.8,
    endgameSkill: 0.7,
    introLine: "I am Tactic Titan. I calculate deep tactical combinations. Watch out for double checks and sacrifices.",
    playerWinLine: "Brilliant! You calculated just as deeply and avoided all my traps.",
    playerLossLine: "Caught you! A tactical combination won your rook. Always check all candidate moves.",
    drawLine: "A draw. A high-level tactical battle with equal play.",
    taunts: ["Did you calculate this line?", "Checking all candidates.", "A tactical trap is set!"],
    mood: "confident",
    difficultyLabel: "Medium"
  },
  {
    id: "intermediate_8",
    tier: "intermediate",
    level: 8,
    name: "Checkstorm King",
    title: "The Intermediate Boss",
    eloTarget: 1500,
    personality: "Very powerful balanced engine. Defeating him unlocks the Hard tier.",
    style: "balanced",
    engine: "nnue",
    depth: 5,
    errorNoiseCp: 40,
    aggression: 0.6,
    defense: 0.7,
    openingKnowledge: 0.8,
    endgameSkill: 0.8,
    introLine: "I am the Checkstorm King, the boss of the Intermediate tier. Defeat me, and you enter the Hard ranks.",
    playerWinLine: "Magnificent! You have defeated the Checkstorm King. Hard tier is now unlocked.",
    playerLossLine: "Not quite. My balanced play squeezed you in the end. Review your matches and try again.",
    drawLine: "A draw. A solid attempt, but you must win to get promoted.",
    taunts: ["Can you handle the pressure?", "The boss fight of Intermediate.", "A balanced board is my strength."],
    mood: "confident",
    difficultyLabel: "Medium"
  },

  // 6. HARD TIER (1500-2000 ELO, 8 characters)
  {
    id: "hard_1",
    tier: "hard",
    level: 1,
    name: "Iron Pawnlord",
    title: "Pawn Chain Builder",
    eloTarget: 1560,
    personality: "Constructs unbreakable pawn chains. Plays extremely solid positional chess.",
    style: "defensive",
    engine: "nnue",
    depth: 5,
    errorNoiseCp: 20,
    aggression: 0.4,
    defense: 0.8,
    openingKnowledge: 0.8,
    endgameSkill: 0.8,
    introLine: "I am Iron Pawnlord. My pawn structures are ironclad. Let's see you try to break through.",
    playerWinLine: "Unbelievable. You cracked my pawn structure and won. Excellent strategy.",
    playerLossLine: "My pawn chain restricted your pieces completely. Positional structure is everything.",
    drawLine: "A draw. A blocked position with no way to break through.",
    taunts: ["Iron walls are up.", "No entry in my center.", "My pawn structure is solid."],
    mood: "intense",
    difficultyLabel: "Hard"
  },
  {
    id: "hard_2",
    tier: "hard",
    level: 2,
    name: "Dark Bishop",
    title: "Shadow Diagonals",
    eloTarget: 1620,
    personality: "Controls the dark squares with extreme accuracy. Hard to pin.",
    style: "tactical",
    engine: "nnue",
    depth: 6,
    errorNoiseCp: 20,
    aggression: 0.6,
    defense: 0.7,
    openingKnowledge: 0.8,
    endgameSkill: 0.8,
    introLine: "I am the Dark Bishop. I dominate the dark squares. Your light pieces won't save you.",
    playerWinLine: "Incredible. You coordinated your pieces and won the dark square battle.",
    playerLossLine: "My dark-squared bishop controlled the entire board. You must contest key colors.",
    drawLine: "A draw. An equal standoff on the diagonals.",
    taunts: ["The dark squares are mine.", "Can you see the diagonal sniper?", "Diagonals are locked down."],
    mood: "intense",
    difficultyLabel: "Hard"
  },
  {
    id: "hard_3",
    tier: "hard",
    level: 3,
    name: "Knight Phantom",
    title: "The Outpost Spectre",
    eloTarget: 1680,
    personality: "Finds unbelievable outpost squares for knights that disrupt your entire board.",
    style: "tactical",
    engine: "nnue",
    depth: 6,
    errorNoiseCp: 20,
    aggression: 0.7,
    defense: 0.6,
    openingKnowledge: 0.9,
    endgameSkill: 0.8,
    introLine: "I am Knight Phantom. My knights occupy squares you cannot defend. Prepare to be disrupted.",
    playerWinLine: "Superb. You denied my outposts and outplayed me. Respect.",
    playerLossLine: "My knight occupied a permanent outpost on d6. That restricted your entire army. Good game.",
    drawLine: "A draw. A hard-fought game where minor pieces were balanced.",
    taunts: ["A ghost knight on d6!", "outposts are key.", "Spotting the outpost before it hurts?"],
    mood: "intense",
    difficultyLabel: "Hard"
  },
  {
    id: "hard_4",
    tier: "hard",
    level: 4,
    name: "Rook Crusher",
    title: "Heavy Artillery",
    eloTarget: 1740,
    personality: "Uses heavy pieces to breach your defense. Loves open files and endgames.",
    style: "balanced",
    engine: "nnue",
    depth: 6,
    errorNoiseCp: 20,
    aggression: 0.6,
    defense: 0.8,
    openingKnowledge: 0.9,
    endgameSkill: 0.9,
    introLine: "I am Rook Crusher. My rooks are heavy artillery. They will blow open your king's shelter.",
    playerWinLine: "Outstanding. You defended your ranks and won a very tough rook endgame.",
    playerLossLine: "My rooks dominated the open files and crushed your back rank. Back rank safety is key.",
    drawLine: "A draw. A balanced rook endgame where neither could win.",
    taunts: ["Contesting the open file!", "Rooks are doubled.", "Headed for the rook endgame."],
    mood: "intense",
    difficultyLabel: "Hard"
  },
  {
    id: "hard_5",
    tier: "hard",
    level: 5,
    name: "Queen Venom",
    title: "Poison Attacks",
    eloTarget: 1800,
    personality: "Aggressive and sharp. Uses double attacks and queen checks constantly.",
    style: "aggressive",
    engine: "nnue",
    depth: 7,
    errorNoiseCp: 20,
    aggression: 0.9,
    defense: 0.5,
    openingKnowledge: 0.9,
    endgameSkill: 0.9,
    introLine: "I am Queen Venom. My attacks are poison. One mistake, and your position collapses.",
    playerWinLine: "Amazing! You kept your king safe, parried my attacks, and won.",
    playerLossLine: "Checkmate. My queen venom took effect. King safety is a top priority.",
    drawLine: "A draw. The queens were traded, and the venom was neutralized.",
    taunts: ["One mistake and you're poisoned.", "My queen is very active.", "Can you survive the venom?"],
    mood: "intense",
    difficultyLabel: "Hard"
  },
  {
    id: "hard_6",
    tier: "hard",
    level: 6,
    name: "Fortress King",
    title: "Unshakable Shield",
    eloTarget: 1860,
    personality: "Very passive but extremely safe. Rarely makes mistake; tests your patience.",
    style: "defensive",
    engine: "nnue",
    depth: 7,
    errorNoiseCp: 20,
    aggression: 0.3,
    defense: 0.9,
    openingKnowledge: 0.9,
    endgameSkill: 0.9,
    introLine: "I am Fortress King. My shield is unshakable. I rarely make a mistake. Prepare for a long struggle.",
    playerWinLine: "Superb. You dismantled my fortress piece by piece. Incredible patience.",
    playerLossLine: "You ran out of patience, made a small mistake, and I punished it. Patience wins games.",
    drawLine: "A draw. A total structural deadlock where neither could progress.",
    taunts: ["Unshakable shield.", "No entry here.", "Patience test."],
    mood: "intense",
    difficultyLabel: "Hard"
  },
  {
    id: "hard_7",
    tier: "hard",
    level: 7,
    name: "Shadow Gambit",
    title: "Deep Preparation",
    eloTarget: 1920,
    personality: "Uses deeply studied openings and sharp tactics to gain a quick edge.",
    style: "aggressive",
    engine: "nnue",
    depth: 7,
    errorNoiseCp: 20,
    aggression: 0.8,
    defense: 0.6,
    openingKnowledge: 0.95,
    endgameSkill: 0.9,
    introLine: "Welcome. I am Shadow Gambit. My opening preparation runs deep. Prepare to defend.",
    playerWinLine: "Excellent. You neutralized my opening prep and outplayed me in the middlegame.",
    playerLossLine: "You fell right into my opening preparation. Opening study is vital at this level.",
    drawLine: "A draw. A sharp theoretical line that ended in equal play.",
    taunts: ["Theoretical preparation!", "Sharpening the lines.", "Deep theory in action."],
    mood: "intense",
    difficultyLabel: "Hard"
  },
  {
    id: "hard_8",
    tier: "hard",
    level: 8,
    name: "Crown Breaker",
    title: "The Hard Boss",
    eloTarget: 2000,
    personality: "Flawless tactical play. Highly aggressive and punishing.",
    style: "balanced",
    engine: "nnue",
    depth: 7,
    errorNoiseCp: 20,
    aggression: 0.7,
    defense: 0.8,
    openingKnowledge: 0.95,
    endgameSkill: 0.95,
    introLine: "I am Crown Breaker, the boss of the Hard tier. This is where your journey meets a wall.",
    playerWinLine: "Incredible! You broke the Crown Breaker. You are ready for the Master Cup tournaments.",
    playerLossLine: "My tactical play punished your slip-ups. Hard tier boss remains undefeated. Try again.",
    drawLine: "A draw. You fought well, but you must defeat me to unlock Master.",
    taunts: ["This is the wall.", "Can you survive the hard boss?", "No crown for you today."],
    mood: "intense",
    difficultyLabel: "Hard"
  },

  // 7. MASTER TIER - 3 CUPS (2000-2500 ELO, 12 characters)
  // Bronze Crown Cup (Cup 1)
  {
    id: "master_1_1",
    tier: "master",
    level: 1,
    cup: 1,
    name: "Bronze Bishop",
    title: "Bronze Cup Match 1",
    eloTarget: 2050,
    personality: "Fianchetto specialist. Sneaky sniper attacks from long range.",
    style: "tactical",
    engine: "nnue",
    depth: 8,
    errorNoiseCp: 10,
    aggression: 0.6,
    defense: 0.8,
    openingKnowledge: 0.95,
    endgameSkill: 0.95,
    introLine: "Welcome to the Bronze Crown Cup. I am Bronze Bishop. Let us contested the board honorably.",
    playerWinLine: "Splendid. Your positional understanding was superior. Good luck in the next match.",
    playerLossLine: "Victory goes to the bishop this day. A noble effort, challenger.",
    drawLine: "A draw. An equal trade of minor piece masterclass.",
    taunts: ["Contesting the long diagonal.", "A noble struggle.", "Watch the fianchetto bishop."],
    mood: "noble",
    difficultyLabel: "Master"
  },
  {
    id: "master_1_2",
    tier: "master",
    level: 2,
    cup: 1,
    name: "Rook Commander",
    title: "Bronze Cup Match 2",
    eloTarget: 2100,
    personality: "Excellent endgame skill. Fights for rook activity and pawn promotion.",
    style: "endgame",
    engine: "nnue",
    depth: 8,
    errorNoiseCp: 10,
    aggression: 0.6,
    defense: 0.8,
    openingKnowledge: 0.95,
    endgameSkill: 0.98,
    introLine: "I am Rook Commander. I excel in rooks endgames. Make sure your structures are clean.",
    playerWinLine: "Impressive! You coordinated your rooks and pawns perfectly in the endgame.",
    playerLossLine: "My rooks found active positions and won. The endgame demands absolute precision.",
    drawLine: "A draw. The rooks ended in a balanced standoff.",
    taunts: ["Into the rook ending.", "Contesting the ranks.", "Precision is key."],
    mood: "noble",
    difficultyLabel: "Master"
  },
  {
    id: "master_1_3",
    tier: "master",
    level: 3,
    cup: 1,
    name: "Knight Emperor",
    title: "Bronze Cup Match 3",
    eloTarget: 2150,
    personality: "Positional squeeze. Constantly builds outposts and restricts your pieces.",
    style: "defensive",
    engine: "nnue",
    depth: 8,
    errorNoiseCp: 10,
    aggression: 0.5,
    defense: 0.9,
    openingKnowledge: 0.95,
    endgameSkill: 0.95,
    introLine: "I am Knight Emperor. I build strong outposts. Let us see how you handle my positional squeeze.",
    playerWinLine: "Superb positional play! You restricted my knights and won the strategic battle.",
    playerLossLine: "My knights occupied key central squares. A structural squeeze is hard to escape.",
    drawLine: "A draw. A balanced positional battle.",
    taunts: ["Squeezing the position.", "Knights occupy the center.", "A strategic challenge."],
    mood: "noble",
    difficultyLabel: "Master"
  },
  {
    id: "master_1_4",
    tier: "master",
    level: 4,
    cup: 1,
    name: "Crown Sentinel",
    title: "Bronze Cup Final",
    eloTarget: 2200,
    personality: "Sharp combination player. Will punish any inaccuracy with immediate tactics.",
    style: "tactical",
    engine: "nnue",
    depth: 8,
    errorNoiseCp: 10,
    aggression: 0.8,
    defense: 0.7,
    openingKnowledge: 0.95,
    endgameSkill: 0.95,
    introLine: "I am Crown Sentinel. This is the Bronze Cup Final. Show me your master-level tactics.",
    playerWinLine: "Brilliant! You won the Bronze Cup. You have proven your master potential.",
    playerLossLine: "Victory is mine. You missed the critical combination. Bronze Cup stays here.",
    drawLine: "A draw. The final continues as a tie.",
    taunts: ["The final test of the Bronze Cup.", "Tactics are sharp today.", "No mistakes allowed here."],
    mood: "noble",
    difficultyLabel: "Master"
  },

  // Royal Crown Cup (Cup 2)
  {
    id: "master_2_1",
    tier: "master",
    level: 5,
    cup: 2,
    name: "Royal Gambiteer",
    title: "Royal Cup Match 1",
    eloTarget: 2250,
    personality: "Plays double-edged gambits with extreme tactical accuracy.",
    style: "aggressive",
    engine: "nnue",
    depth: 9,
    errorNoiseCp: 10,
    aggression: 0.9,
    defense: 0.6,
    openingKnowledge: 0.98,
    endgameSkill: 0.95,
    introLine: "Welcome to the Royal Cup. I am Royal Gambiteer. A double-edged gambit tests your courage.",
    playerWinLine: "Excellent defense! You absorbed the pressure and won. Good luck in the next round.",
    playerLossLine: "My gambit succeeded. Initiative is a powerful force in master chess.",
    drawLine: "A draw. A theoretical line that ended in equal coordinates.",
    taunts: ["Courage is needed.", "Do you accept the gambit?", "Tactical lines are sharp."],
    mood: "noble",
    difficultyLabel: "Master"
  },
  {
    id: "master_2_2",
    tier: "master",
    level: 6,
    cup: 2,
    name: "Queen Astra",
    title: "Royal Cup Match 2",
    eloTarget: 2300,
    personality: "Forces complicated middle games. Master of heavy piece coordination.",
    style: "tactical",
    engine: "nnue",
    depth: 9,
    errorNoiseCp: 10,
    aggression: 0.8,
    defense: 0.8,
    openingKnowledge: 0.98,
    endgameSkill: 0.96,
    introLine: "I am Queen Astra. I coordinate heavy pieces in complex middle games. Let's see your planning.",
    playerWinLine: "Magnificent coordination! You outplayed me in a very complex position.",
    playerLossLine: "My heavy pieces dominated the board. Coordination is the key to victory.",
    drawLine: "A draw. Both queens survived the intense battle.",
    taunts: ["Coordinating the heavy pieces.", "A complex board.", "Watch the Queen's lines."],
    mood: "noble",
    difficultyLabel: "Master"
  },
  {
    id: "master_2_3",
    tier: "master",
    level: 7,
    cup: 2,
    name: "Bishop Monarch",
    title: "Royal Cup Match 3",
    eloTarget: 2350,
    personality: "Fabulous positional squeezes. Plays solid, error-free chess.",
    style: "defensive",
    engine: "nnue",
    depth: 9,
    errorNoiseCp: 10,
    aggression: 0.4,
    defense: 0.9,
    openingKnowledge: 0.98,
    endgameSkill: 0.97,
    introLine: "I am Bishop Monarch. I squeeze the position slowly. A minor mistake will cost you the game.",
    playerWinLine: "Superb. Your positional accuracy was flawless. A masterpiece.",
    playerLossLine: "You allowed me to squeeze your files. Positional accuracy is vital.",
    drawLine: "A draw. A structural deadlock with equal coordinates.",
    taunts: ["Squeezing the lines.", "A patient positional game.", "No weaknesses in my camp."],
    mood: "noble",
    difficultyLabel: "Master"
  },
  {
    id: "master_2_4",
    tier: "master",
    level: 8,
    cup: 2,
    name: "Royal Warden",
    title: "Royal Cup Final",
    eloTarget: 2400,
    personality: "Unbelievable defensive calculator. Saves drawing positions with ease.",
    style: "defensive",
    engine: "nnue",
    depth: 9,
    errorNoiseCp: 10,
    aggression: 0.5,
    defense: 0.95,
    openingKnowledge: 0.98,
    endgameSkill: 0.98,
    introLine: "I am Royal Warden. This is the Royal Cup Final. Let us contested the board with all our skills.",
    playerWinLine: "Outstanding! You broke my defense and won the Royal Cup. Magnificent chess.",
    playerLossLine: "My defense held, and I won on the counter. Royal Cup stays with the Warden.",
    drawLine: "A draw. The final is a deadlock.",
    taunts: ["The Royal Cup Final.", "My defense is solid.", "A noble battle."],
    mood: "noble",
    difficultyLabel: "Master"
  },

  // Emperor Crown Cup (Cup 3)
  {
    id: "master_3_1",
    tier: "master",
    level: 9,
    cup: 3,
    name: "Phantom Rook",
    title: "Emperor Cup Match 1",
    eloTarget: 2425,
    personality: "Positional rook endings. Punishes minor pawn structure weaknesses.",
    style: "endgame",
    engine: "nnue",
    depth: 10,
    errorNoiseCp: 10,
    aggression: 0.6,
    defense: 0.9,
    openingKnowledge: 0.99,
    endgameSkill: 0.99,
    introLine: "Welcome to the Emperor Cup. I am Phantom Rook. Rook endgames are my domain.",
    playerWinLine: "Superb. Your rook endgame technique was absolutely flawless.",
    playerLossLine: "My active rook won the pawns. Rooks must remain active in the endgame.",
    drawLine: "A draw. The rooks were traded to a dead draw.",
    taunts: ["Into the rook endgame.", "Active rooks are key.", "A structural challenge."],
    mood: "noble",
    difficultyLabel: "Master"
  },
  {
    id: "master_3_2",
    tier: "master",
    level: 10,
    cup: 3,
    name: "Silent Queen",
    title: "Emperor Cup Match 2",
    eloTarget: 2450,
    personality: "Keeps the position extremely tight, then strikes with lethal counterattacks.",
    style: "balanced",
    engine: "nnue",
    depth: 10,
    errorNoiseCp: 10,
    aggression: 0.6,
    defense: 0.9,
    openingKnowledge: 0.99,
    endgameSkill: 0.98,
    introLine: "I am Silent Queen. My position is tight, and my counter-attacks are lethal. Focus is required.",
    playerWinLine: "Amazing! You broke my position, defended my counter-attacks, and won.",
    playerLossLine: "My counter-attack succeeded. You left a weak square, and I struck.",
    drawLine: "A draw. A balanced match with high-level play.",
    taunts: ["Tight position.", "Waiting for the strike.", "Coordination is key."],
    mood: "noble",
    difficultyLabel: "Master"
  },
  {
    id: "master_3_3",
    tier: "master",
    level: 11,
    cup: 3,
    name: "Grand Bishop",
    title: "Emperor Cup Match 3",
    eloTarget: 2475,
    personality: "Controls key diagonals and outposts. Near flawless execution.",
    style: "balanced",
    engine: "nnue",
    depth: 10,
    errorNoiseCp: 10,
    aggression: 0.7,
    defense: 0.8,
    openingKnowledge: 0.99,
    endgameSkill: 0.99,
    introLine: "I am Grand Bishop. Let us contested the board with honor. My diagonals are fully covered.",
    playerWinLine: "Splendid! You outplayed me positional and earned a noble victory.",
    playerLossLine: "My bishop pair dominated the diagonals. A noble victory for the Grand Bishop.",
    drawLine: "A draw. An equal match of structural chess.",
    taunts: ["Contesting the board.", "A noble game.", "Diagonals are locked."],
    mood: "noble",
    difficultyLabel: "Master"
  },
  {
    id: "master_3_4",
    tier: "master",
    level: 12,
    cup: 3,
    name: "Emperor Kaal",
    title: "Emperor Cup Final Boss",
    eloTarget: 2500,
    personality: "Fearsome final boss of Master tier. Defeating him opens Grandmaster.",
    style: "tactical",
    engine: "nnue",
    depth: 10,
    errorNoiseCp: 10,
    aggression: 0.8,
    defense: 0.9,
    openingKnowledge: 0.99,
    endgameSkill: 0.99,
    introLine: "I am Emperor Kaal. This is the Emperor Cup Final. Defeat me, and you unlock the Grandmaster rank.",
    playerWinLine: "Incredible! You have defeated Emperor Kaal and won the Emperor Cup. Welcome to Grandmaster.",
    playerLossLine: "My tactical execution was absolute. Emperor Kaal remains undefeated. Try again, noble challenger.",
    drawLine: "A draw. You fought bravely, but you must win to claim the Emperor Cup.",
    taunts: ["This is the ultimate trial.", "Can you defeat the Emperor?", "No mistakes are tolerated here."],
    mood: "noble",
    difficultyLabel: "Master"
  },

  // 8. GRANDMASTER TIER (2500+ ELO, 3 characters)
  {
    id: "grandmaster_1",
    tier: "grandmaster",
    level: 1,
    name: "Crownless King",
    title: "The Grandmaster Boss",
    eloTarget: 2600,
    personality: "The supreme boss. Requires 2 wins in a best-of-3 series. Plays near perfect chess.",
    style: "balanced",
    engine: "nnue",
    depth: 12,
    errorNoiseCp: 0,
    aggression: 0.8,
    defense: 0.95,
    openingKnowledge: 1.0,
    endgameSkill: 1.0,
    introLine: "I am the Crownless King. You have reached the summit. Show me your legendary chess.",
    playerWinLine: "Unbelievable... you have defeated the Crownless King. A legendary victory, Grandmaster.",
    playerLossLine: "The board behaves exactly as I foresaw. You must study deeper to defeat a Grandmaster.",
    drawLine: "A draw against me? A historic achievement, indeed.",
    taunts: ["I see many moves ahead.", "A bold attempt, but the position is mine.", "Every square is under my control."],
    mood: "legendary",
    difficultyLabel: "Grandmaster"
  },
  {
    id: "grandmaster_2",
    tier: "grandmaster",
    level: 2,
    name: "Oracle Knight",
    title: "Daily Challenger",
    eloTarget: 2700,
    personality: "Daily puzzle specialist. Changes playstyle daily to challenge your mind.",
    style: "tactical",
    engine: "nnue",
    depth: 14,
    errorNoiseCp: 0,
    aggression: 0.8,
    defense: 0.8,
    openingKnowledge: 1.0,
    endgameSkill: 0.99,
    introLine: "I am the Oracle Knight. My strategies change with the rising sun. Can you solve my board today?",
    playerWinLine: "Splendid! You solved my lines and won a legendary victory.",
    playerLossLine: "My daily puzzle remained unsolved. Review the positions and try again tomorrow.",
    drawLine: "A draw. An equal standoff against the Oracle.",
    taunts: ["Can you solve this puzzle?", "Tactics change daily.", "Watch the knight moves closely."],
    mood: "legendary",
    difficultyLabel: "Grandmaster"
  },
  {
    id: "grandmaster_3",
    tier: "grandmaster",
    level: 3,
    name: "Grandmaster Veyron",
    title: "Seasonal Prestige Rival",
    eloTarget: 2800,
    personality: "Legendary rival. Flawless openings, hyper-accurate endgames. Zero tolerance for errors.",
    style: "balanced",
    engine: "nnue",
    depth: 16,
    errorNoiseCp: 0,
    aggression: 0.9,
    defense: 0.95,
    openingKnowledge: 1.0,
    endgameSkill: 1.0,
    introLine: "I am Grandmaster Veyron, the pinnacle of the seasonal ranks. Let us contested the board. Zero errors are tolerated.",
    playerWinLine: "Magnificent! You have defeated Veyron. You are the ultimate prestige champion.",
    playerLossLine: "You made a single positional mistake, and I punished it. Precision is the mark of a Grandmaster.",
    drawLine: "A draw. A historic match of absolute accuracy.",
    taunts: ["Flawless openings.", "Accuracy is absolute.", "Zero tolerance for errors."],
    mood: "legendary",
    difficultyLabel: "Grandmaster"
  }
];
