use crate::rooms::room_errors::RoomError;
use hmac::{Hmac, Mac};
use sha2::Sha256;

pub const SUPPORTED_PROTOCOL_VERSION: &str = "1.0.0";

type HmacSha256 = Hmac<Sha256>;

/// Verifies the session token generated by the Node.js backend.
/// Boundary: Firebase ID token is verified by the Node.js backend using Firebase Admin SDK,
/// and the short-lived session token (HMAC-signed with SESSION_TOKEN_SECRET) is verified here by Rust.
/// Rust extracts the authoritative UID from the verified token.
pub fn verify_token_dev_or_firebase_later(
    client_supplied_uid: Option<&str>,
    token: Option<&str>,
    protocol_version: Option<&str>,
) -> Result<String, RoomError> {
    // 1. Verify protocol version
    let version = protocol_version.unwrap_or("");
    if version != SUPPORTED_PROTOCOL_VERSION {
        return Err(RoomError::ProtocolVersionMismatch {
            expected: SUPPORTED_PROTOCOL_VERSION.to_string(),
            got: version.to_string(),
        });
    }

    // Dev mode bypass only if explicitly configured in DEV_MODE env or under test
    let dev_mode = cfg!(test)
        || std::env::var("DEV_MODE")
            .map(|v| v == "true" || v == "1")
            .unwrap_or(false);
    if dev_mode && (token.is_none() || token == Some("dev_mock_token")) {
        return Ok(client_supplied_uid.unwrap_or("dev_user").to_string());
    }

    let token_str = token.ok_or(RoomError::AuthRequired)?;

    // Split token by ":" - Format: uid:expires_at:signature
    let parts: Vec<&str> = token_str.split(':').collect();
    if parts.len() != 3 {
        return Err(RoomError::AuthFailed("Invalid token format".to_string()));
    }

    let token_uid = parts[0];
    let expires_at_str = parts[1];
    let signature_hex = parts[2];

    // Expiration check
    let expires_at = expires_at_str
        .parse::<i64>()
        .map_err(|_| RoomError::AuthFailed("Invalid expiration time".to_string()))?;

    let now = chrono::Utc::now().timestamp_millis();
    if now > expires_at {
        return Err(RoomError::AuthFailed("Token expired".to_string()));
    }

    // Signature check
    let secret = std::env::var("SESSION_TOKEN_SECRET")
        .unwrap_or_else(|_| "default_session_secret".to_string());

    let data = format!("{}:{}", token_uid, expires_at_str);

    let mut mac = HmacSha256::new_from_slice(secret.as_bytes())
        .map_err(|_| RoomError::AuthFailed("Failed to initialize HMAC".to_string()))?;
    mac.update(data.as_bytes());

    let result = mac.finalize();
    let code_bytes = result.into_bytes();
    let expected_sig = hex::encode(code_bytes);

    if expected_sig != signature_hex {
        return Err(RoomError::AuthFailed("Invalid signature".to_string()));
    }

    Ok(token_uid.to_string())
}
